import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Crescent School",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
    return (
        <nav className="flex w-full items-center justify-between border-b p-4 text-xl font-semibold">
         <div>Logo</div> 
         <div>Administrative</div>
         <div>Gaming</div>
         <div>Bartending</div>
         <div>Special Programs</div>
         <div>Disbursements</div>
         <div>Reports</div>
         <div> Sign In</div>
        </nav>
    );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col gap-4">
        <TopNav />
      {children}
      </body>
    </html>
  );
}
