import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { Nav_Bar } from "./_components/Nav_Bar";

export const metadata: Metadata = {
  title: "Crescent School",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
  <html lang="en" className={`${GeistSans.variable}`}>
    <body className="flex flex-col gap-4">
      <Nav_Bar />
      {children}
    </body>
  </html>
  );
}
